### ISSUE TITLE
Animated Priority on Animation Player can't start at scene start.

### ISSUE THREAD

**Issue by yalazur** [ramokz/phantom-camera#100]
Hello, im looking to creating a cut scene, here is what i did.

Create a Camera3D,
Add pcam host as the child,
add 2 pcam as child of Node3D,
pcam 1 with priority1,
pcam 2 with priority 0 and then goes trough 2,
add animation player
add a property track of pcam2 priority into the animation player
first 2 secs of pcam2 the priority is 0, and then from then onward the priority is 2.
i enabled play animation on load
and i tested it in viewport and its a succsess, the pcam succsessfully transition between 2 cameras.
however when i play it as a scene, nothing happened.

heres the report on the debugger:
![image](https://github.com/ramokz/phantom-camera/assets/113665849/900b84d5-fc47-4b8e-9905-e13a17c22677)
![image](https://github.com/ramokz/phantom-camera/assets/113665849/d3990fe6-8435-4854-b93c-ddba223b5bfc)

Much thanks for the awesome plugin!

closed: i found out that i was having multiple camera 3D and not only the MainCamera3D, when there is only a singular Camera3D in the scene, it worked.

**Comment by yalazur** [comment]
nvm, i tried adding one more Pcam, and it didn't work, i tried to ctrl z it to the initial condition and it wouldn't work.

**Comment by ramokz** [comment]
Had a go with the setup you described above. It appears to be working fine both in the viewport and when playing the scene.

Have attached the scene that I'm testing with, does that setup match what you're trying to do?
[Issue_#100_scene.tscn.zip](https://github.com/ramokz/phantom-camera/files/11643408/Issue_.100_scene.tscn.zip)

As for the debugger reports, that appears to be what is being tracked in #99. Which is to say, it's false positive errors that Godot is outputting.

**Comment by yalazur** [comment]
yes thats exactly is my setup, although my priority change is based on timeline keyframe and not based on click interactivity.

![image](https://github.com/ramokz/phantom-camera/assets/113665849/def95716-b94a-4bc7-af66-990d0431df55)

so, after a bit of tinkering, i have succsessfully did my scene if i set the priorty keyframe as a bezier track instead of a property track...

**Comment by ramokz** [comment]
Am not entirely sure what the click interactivity is, but the scene I sent should be using the Property Track, with the `priority` property being the only thing that's changing.
![image](https://github.com/ramokz/phantom-camera/assets/5159399/44463654-1a11-428c-8e15-1ad40ef94322)

Unfortunately, I'm unable to open and check the scene you sent due to missing resource files that's linked to it.

**Comment by yalazur** [comment]
im sorry that was my bad, i looked on the RESET track and found no keyframe, i thought it was interactive and was clicking trough the scene debugger and thought it was interactive....

i've checked again and you are right, it is property track, and i've gone and try it again (setting keyframe with property track), and now it worked.... i honestly don't know how could that be...

just so that i'm not totally wasting ur time... i want to add some detail that I remembered last night from that "nothing happened".. just in case someone stumbled upon the same problem,

so, the nothing happened was: the camera was stuck in pcam2 position, and when i checked, it turned out that the 2 keyframes property are suddenly all 2 (when i had set them to be 0 and 2 before). and thats it,

thankyou for your time and sorry for the incovenience, cheers!

**Comment by ramokz** [comment]
No problem! Glad to hear it worked out 🙂
