### ISSUE TITLE
Rotate around look-at target

### ISSUE THREAD

**Issue by Mondanzo** [ramokz/phantom-camera#110]
### Project Type

3D

### Feature Description

at the moment there is no simple way to just let the camera rotate around the target with the positional offset.

### Use Cases

One example would be to have a 2D game in 3d space which simply follows the players orientation. While keeping the other features like framing and dampening.
![danzo_XixO5Ta6h6](https://github.com/ramokz/phantom-camera/assets/14519085/7a0b9884-6eb6-4e7f-a03f-ebec19e4b295)

### Importance

Low - there are workarounds where the proposed feature would just simplify things

### Usage

All the time - the feature can be very useful for a varity of different projects

### (Optional) Proposed Solution

This could be implemented as a simple bool in addition to the look at modes to just be something like "rotate around target". Then the offset position needs to be rotated by the rotation the look at target gets. Mainly useful for simple and glued.

**Comment by ramokz** [comment]
Think this is a very good proposal and can definitely see its usefulness.
Framed Follow already has an orbit-like rotation behavior, so can't imagine it'll be too difficult to add this as well.

**Comment by tiloc** [comment]
Would this be similar to Orbital Follow mode in CineMachine?

**Comment by ramokz** [comment]
Think this could also be achieved using `Third Person` follow?
Would just need to apply the rotational setter methods as the character turns.

**Comment by ramokz** [comment]
Closing this issue per the above suggestion.
Think anything beyond that will creep into a fairly complex solution that effectively just simplifies what `Third Person` follow can already do.

Feel free to suggest reopening this if there are other opinions, and we can continue the conversation.
