### ISSUE TITLE
Third Person Follow Rotation Override

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#113]
### Project Type

3D

### Feature Description

When setting the Follow mode, in 3D scenes, to Third Person by default it won't do much beyond adding a `springarm` node. Typically, there is a need for having some way of move the camera around the target one way or another.

This is possible to do via code, but requires strapping additional logic onto the code injected `springarm` node, which is cumbersome to say the least.

To improve the DX, having an easy way to bind rotation logic is desirable.

### Use Cases

Pretty much whenever the Follow Mode is set to Third Person Follow. Needs an additional script to have rotational logic applied to it.

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

Often - a significant amount of projects can find this useful

### (Optional) Proposed Solution

- Add a setter method for applying rotational values to the `springarm` via code. This should allow for controlling the camera's rotation from anywhere that can access the `PCam3D` node.
- Offer an optional preset for binding mouse and gamepad to control the camera's rotation. This is to provide a simple out-of-box option.
  - Presets should have overrideable variables for things like mouse sensitivity and max/min yaw/pitch

**Comment by ramokz** [comment]
Added getters and setters for changing the `SpringArm3D` rotation and used it in the example scene.

Decided to not include out-of-box solutions at this time as the behaviour implementation will wound up being too opinionated, which I can imagine could cause conflicts with other logic in a given project. Open to be revisited in the future.
The wiki page will instead provide code examples for how to use the setter/getter.

**Comment by denishacquin** [comment]
Unfortunately, it seems the methods change the rotation of the pcam itself and doesn't make the camera orbit around the target like the documentation suggests.

**Comment by ramokz** [comment]
Which methods are you referring to?

`set_third_person_rotation()` and `set_third_person_rotation_degrees()` should both only affect the `SpringArm3D` node if you have the `Follow Mode` set to `Third Person`.

Can see an example in the demo scene.
