### ISSUE TITLE
Assigning nodes to look at via code does not work for look at mode "Group"

### ISSUE THREAD

**Issue by mharitsnf** [ramokz/phantom-camera#119]
### Issue description

I am developing an enemy "lock-on" system like in Elden Ring or Zelda games, which requires me to use the "Group" look at mode to add / remove look at targets via code.

It works like wonders when I assign the node targets directly via the editor, but it's not working when I do it via code. The camera doesn't seem to respond to the change at all. I am using the functions `append_look_at_group_node` and `erase_look_at_group_node` to add and remove the nodes. Here's a clip from a test project I made:

https://github.com/ramokz/phantom-camera/assets/22760908/b2e19cf3-b4b4-417e-b81b-d5d730afd09e

I couldn't find a similar a similar issue, but I'm sorry if I'm making a duplicate.

### Steps to reproduce

- Install the plugin from the asset store
- Setup the PhantomCameraHost and a PhantomCamera3D
- Add a couple of targets to look at
- Set the look at mode to be "Group", but don't add the targets via the editor
- Make a script that add the target when you press something using the `append_look_at_group_node()` function

### (Optional) Minimal reproduction project

[PhantomCameraMRP.zip](https://github.com/ramokz/phantom-camera/files/12868822/PhantomCameraMRP.zip)

I'm using Godot 4.1.1. Run the Main scene to try it out. I set up two Phantom cameras, both using the look at "Group" mode. I assigned the targets directly in the editor for the `EditorLookAt` node, and the targets for the `CodeLookAt` node is added from the script.

I hope everything clear enough!

**Comment by ramokz** [comment]
Good spot and well documented, this was an unknown bug!

Have attached an update version of `phantom_camera_3D.gd`, which should have a fix for that.
It worked when I updated this in the project you sent (thanks for providing that).

Give that a whirl by replacing the existing one inside `addons/phantom_camera/scripts/phantom_camera/` and see if it works for you as well.

[phantom_camera_3D.gd.zip](https://github.com/ramokz/phantom-camera/files/12874485/phantom_camera_3D.gd.zip)

**Comment by mharitsnf** [comment]
Tried it, and it works perfectly. Thanks for the help!

**Comment by ramokz** [comment]
Closing as issue has now been updated in the main branch – minor release pending.
