### ISSUE TITLE
null exception on _look_at_target_node when LookAtMode is not None

### ISSUE THREAD

**Issue by matt-seaton** [ramokz/phantom-camera#120]
### Issue description

I've only noticed this in 3rd person follow mode.  

### Steps to reproduce

Set follow mode to 3rd person.  Set look at mode to anything other than None.  Enter play mode.  Null exception on _look_at_target_node occurs.

**Comment by ramokz** [comment]
Good spot! Have applied a fix to this.

Frankly, I have considered hiding the Look At option when applying a Third Person follow, as I can't quite think of a use case for it.

Out of interest, were you looking to achieve anything in particular?
