### ISSUE TITLE
Change follow_group at runtime error

### ISSUE THREAD

**Issue by pikpoket** [ramokz/phantom-camera#121]
### Issue description

Hi, since I'm adding units to my scene in script, I have to append theese units to the PhantomCamera3D follow_group property. I'm using append_follow_group_node with a reference to the unit in question but when I debug I see that the follow_group property haven't changed and is still empty.

I've also tried to directly modify the property with an Array[NodePath] but i got an error _Invalid set index 'follow_group' (on base: 'Node3D (PhantomCamera3D)') with value of type 'Array[NodePath]'._

Have a nice day,

### Steps to reproduce

Open 3DFollowGroupExampleScene
Modify follow_group in script

**Comment by ramokz** [comment]
This sounds similar to #119, does replacing the attached script in the comment in there solve the issue?

**Comment by pikpoket** [comment]
It does not, but maybe is there something I'm missing ? Here's the minimal reproduction project.
[camera_error_reproduction.zip](https://github.com/ramokz/phantom-camera/files/12897052/camera_error_reproduction.zip)

**Comment by ramokz** [comment]
I can see the issue.

It looks like you're trying to fetch the follow group nodes using `$PhantomCamera3D.follow_group`, which isn't a property that exists, and why you're getting that error.

What you can do instead is call the getter method `$PhantomCamera3D.get_follow_group_nodes()`. That will return the nodes as they get instantiated.

**Comment by pikpoket** [comment]
Thanks you for your help !

**Comment by pikpoket** [comment]
Can't directly access properties.
