### ISSUE TITLE
PhantomCamera3D does not follow group if nodes were added in script

### ISSUE THREAD

**Issue by pikpoket** [ramokz/phantom-camera#123]
### Issue description

Hi,

Similarly to #119 PhantomCamera3D does not work when assigning node to the follow group with code.

Thanks for your time,

### Steps to reproduce

Use arrows keys to move the player. The camera does not move.

### (Optional) Minimal reproduction project

[camerra_follow_error.zip](https://github.com/ramokz/phantom-camera/files/12908775/camerra_follow_error.zip)

**Comment by ramokz** [comment]
Have merged a fix for this, if you want a quick fix without waiting for the next release and grabbing the whole thing I've attached an updated `PhantomCamera3D.gd` version here that should resolve the issue.

[phantom_camera_3D.gd.zip](https://github.com/ramokz/phantom-camera/files/12909309/phantom_camera_3D.gd.zip)

**Comment by pikpoket** [comment]
It works like a charm, thanks a lot !
