### ISSUE TITLE
Camera3D Environment and Attributes resource per PhantomCamera

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#127]
### Project Type

3D

### Feature Description

v0.5 introduced `Camera3D` as a resource, which allowed for overriding the `Camera3D` node's property per `PhantomCamera3D`.

The `Camera3D` node also contain properties for `Environment` and `Attributes` resources, that allows for applying e.g. depth of field and general environmental appearances.

### Use Cases

Can be useful in cases where you shift the perspective from a third person to over the shoulder, where once there it would change the depth of field to a larger aperture size to increase the blur effect.

Another example is to rapidly change to a very different colour scheme upon switching to another `PhantomCamera`.

This can be done via code already, where this would just simplify that process.

### Importance

Low - there are workarounds where the proposed feature would just simplify things

### Usage

Rarely - just a handful of projects can likely benefit from this

### (Optional) Proposed Solution

- [ ] Adding additional exportable variables to the `Camera3D` resource that uses `Environment` and `Attributes` as types.
- [ ] Applying those resources upon changing `PhantomCamera`.

**Comment by ZenithStar** [comment]
If/when this gets implemented, I ask that the DoF properties be included in the tweening.

**Comment by ramokz** [comment]
Completed in #355
