### ISSUE TITLE
Crash if `_enter_tree` of Camera2D called before that of PhantomCameraHost

### ISSUE THREAD

**Issue by xchrix** [ramokz/phantom-camera#129]
### Issue description

Godot version:

v4.1.2.stable.official [399c9dc39]

Addons version:

11e2ac50780f81376ca972dc22e6e0f620d31e08

In the demo '2DExampleScene.tscn', switch the 'Camera2D' node and 'Player' node. Now, click 'F6' to run the scene, the scene will crash with the following message:
```
Invalid call. Nonexistent function 'assign_pcam_host' in base 'Node2D (PhantomCamera2D)".
```

### Steps to reproduce

Open the 'crash.tscn', click 'F6' to run. Scene should crash with the message above.

Open the 'no_crash.tscn', click 'F6' to run. Scene runs normally.

[phantom-camera-demo.zip](https://github.com/ramokz/phantom-camera/files/13214650/phantom-camera-demo.zip)

**Comment by ramokz** [comment]
Thanks for spotting this!
