### ISSUE TITLE
Draw phantom camera screen rectangle in editor.

### ISSUE THREAD

**Issue by filipinyo** [ramokz/phantom-camera#131]
### Project Type

2D

### Feature Description

When positioning camera in editor, many of times you have to trial and error where the edges of the phantom camera should are. It'd be awesome if we'd have a this screen rectangle like in camera2d in editor.``

### Use Cases

Easier scene planning.

### Importance

Low - there are workarounds where the proposed feature would just simplify things

### Usage

Often - a significant amount of projects can find this useful

**Comment by ramokz** [comment]
Good proposal! Will get around to this soon.
