### ISSUE TITLE
Camera2D Limits

### ISSUE THREAD

**Issue by spheras** [ramokz/phantom-camera#139]
### Project Type

2D

### Feature Description

Hello (first of all, congratulations on the project, it's amazing).  I miss the ability to set limits to the camera, just like you can do to the 2D camera.  These limits are necessary for games, for example, top style, where the camera should not go out of certain limits.

I think the best idea would be for the phantomCamera2D to have the limit properties (just like the normal Camera2D has), and when the phantom is active, it would pass these properties to the camera.

In fact, I've implemented it this way in the fork of this project in my repo.  You can see the changes in this commit of the fork: https://github.com/spheras/phantom-camera-fork/commit/5b73419c4cfac466e86f5c921969374290604fc0

The changes there are:
- phantom camera now has limits properties (and a limit activation property). Same properties as the real Camera2D limits
- Phantom host now set those limits (if activated in the active phatom camera) to the Camera2D
- A very basic scene to understand the behavior

As I said, I needed this for my personal project, but if this is interesting to you as well, I can do a pull request.

Regards!

### Use Cases

any 2d game that need to set limits:
- top style game
- beatemup style game
- platform style game

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

Often - a significant amount of projects can find this useful

### (Optional) Proposed Solution

As I said, I've implemented the proposal in the fork of this project in my repo.  You can see the changes in this commit of the fork: https://github.com/spheras/phantom-camera-fork/commit/5b73419c4cfac466e86f5c921969374290604fc0

The changes there are:
- phantom camera now has limits properties (and a limit activation property). Same properties as the real Camera2D limits
- Phantom host now set those limits (if activated in the active phatom camera) to the Camera2D
- A very basic scene to understand the behavior

(I tried to mimic your code style as much as possible)

**Comment by ramokz** [comment]
Excellent proposal, and thanks for sharing your fork! Think this would be very nice to add support for.

Have added support for limiting a `PCam2D` to a `TileMap` node in #111. However, think it makes a lot of sense to also have the option that you're proposing, and have done, with the Left, Top, Right, Bottom number input.

Think what I'm going to do is do what you've suggesting in addition to having an automatic variant where specific nodes, like a `TileMap`, could automatically apply those values. Basically, tying those two systems together.
