### ISSUE TITLE
Add multi-host capability

### ISSUE THREAD

**Issue by WeaselOnaStick** [ramokz/phantom-camera#199]
### Project Type

2D, 3D, Editor

### Feature Description

Add the ability to assign different independent phantom camera hosts to different cameras.

### Use Cases

Split-screen games, ["3D Cards"](https://www.youtube.com/watch?v=3l5XIqCrIBQ), CCTV and other uses of general render "portals".

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

Often - a significant amount of projects can find this useful

### (Optional) Proposed Solution

Each pcam host would require an array of pcams to actually use (while ignoring others). It could be just an @export array, better solution would be to use [groups](https://docs.godotengine.org/en/stable/tutorials/scripting/groups.html).

**Comment by ramokz** [comment]
This is planned in #26 for 0.8 release.

**Comment by WeaselOnaStick** [comment]
> This is planned in #26 for 0.8 release.

Sorry, somehow overlooked that one. I guess this should be closed as duplicate.
Looking at #26 I still think best solution would be to have "many-to-many" relationship between hosts and pcams implemented via groups.

**Comment by ramokz** [comment]
No sweat! It's always good to know what others are interested in 🙂

It was written a while back when the project first started, so the approach will be revalued again when works starts on it as a lot has changed.
