### ISSUE TITLE
Updater Doesn't work

### ISSUE THREAD

**Issue by lunarcloud** [ramokz/phantom-camera#201]
### Issue description

The update button does nothing.
And worse, there's no "**don't tell me about this again**" button to prevent it from re-appearing every time I load my project!

### Steps to reproduce

1. Open project ( like say https://github.com/lunarcloud/ggj-2024-rail-shooter/tree/GGJ2024Final )
2. See the update notifier
![image](https://github.com/ramokz/phantom-camera/assets/1565970/e17ada1a-b14f-4d1e-8aea-b3d41041ea52)
3. Click Update
4. Eventually it asks to restart
![image](https://github.com/ramokz/phantom-camera/assets/1565970/d29fb220-a272-40c3-a82e-43efd91b9544)
5. Click "Reload"
6. Nothing has changed, go back to step 2

**Comment by lunarcloud** [comment]
Godot version is 4.2.1 stable on Linux

**Comment by ramokz** [comment]
Apologies, forgot to update the plugin.cfg.

Should be working now if you reopen the project.
