### ISSUE TITLE
Allow user to ignore an update

### ISSUE THREAD

**Issue by lunarcloud** [ramokz/phantom-camera#203]
### Project Type

Editor

### Feature Description

Currently, there's no choice but to see the update screen every project (plugin) reload or update.

### Use Cases

A project that's been released and is on bugfix-only mode would have devs appreciating this.

### Importance

Low - there are workarounds where the proposed feature would just simplify things

### Usage

Often - a significant amount of projects can find this useful

### (Optional) Proposed Solution

It would be great to have the plugin write a project settings like:
-  "phantom_camera/ignore_update" with a value of a date or version
-  "phantom_camera/ignore_all_updates" default false

**Comment by ramokz** [comment]
Good suggestion.

Got a few things planned for the updater in an upcoming minor release, so will add support for this as well when that happens.
