### ISSUE TITLE
Framed camera's Viewfinder_in_play's frame does not despawn when changing camera priority 

### ISSUE THREAD

**Issue by RichardStolp** [ramokz/phantom-camera#208]
### Issue description

The green frame showing the dead zone for framed cameras does not despawn when the priority between two framed cameras is swapped. This causes the green frames to stack until it becomes impossible to see anything else.

https://github.com/ramokz/phantom-camera/assets/20906065/a46ed2da-ebd5-4028-a119-4cc1f4429806

### Steps to reproduce

In the 2DLimitExampleScene set all of the cameras to Framed and toggle on their ViewFinder_in_play option. Run the scene and walk back and fourth between two of the limit boundaries so that the cameras switch. This will cause more and more frames to appear until the screen is just green except for the deadzone.

**Comment by RichardStolp** [comment]
Found in version 0.6.3 of Phantom Camera and version 4.2.1 of Godot.

**Comment by ramokz** [comment]
Can confirm this issue, will be addressed in an upcoming minor release.
