### ISSUE TITLE
Support for orthographic, near, and far Camera3D parameters

### ISSUE THREAD

**Issue by Jegber** [ramokz/phantom-camera#218]
### Project Type

3D

### Feature Description

The Camera 3d resource of a PhantomCamera3D should be able to support all of a Camera3D's parameters, including (missing currently):

- Size (for orthographic cameras)
- Near
- Far
- Maybe Projection? For switching between projection and orthographic views?

### Use Cases

Zooming in on objects of interest in an orthographic 3D game.

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

Often - a significant amount of projects can find this useful

**Comment by ZenithStar** [comment]
If/when this gets implemented, I also ask that the properties be included in the tweening.

**Comment by qiqetes** [comment]
I still cannot change to Orthographic, is that normal?
