### ISSUE TITLE
set_spring_arm_collision_mask for the thrid person camera doesn't work

### ISSUE THREAD

**Issue by eliaskowitz** [ramokz/phantom-camera#222]
### Issue description

using set_spring_arm_collision_mask at runtime doesn't do anything. as far as i can tell from glancing over the phantom camera code it looks like set_collision_mask() is only called once when initializing. i could be wrong but i can't find it anywhere else.

### Steps to reproduce

call set_spring_arm_collision_mask at runtime

**Comment by ramokz** [comment]
No, you are correct. That's an oversight on my part.

The issue also applies to other `SpringArm3D` override setters.
Will be fixed in the upcoming minor release.
