### ISSUE TITLE
Preview PhantomCamera without modifying priority

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#24]
# Problem
When modifying a position or rotation of a `PhantomCamera`, in the Editor, you won't see the framing of it until it becomes active.
In order to preview what it sees / frames, you have to manually set its priority to the highest value. This is not only tedious when changing a scene or moving `PhantomCameras` around, but can also pose a risk due to forgetting to revert the priority value back to what it should be.

# Proposed Solution
Adding a property button that forces a `PhantomCamera` to become active – in spite of not having the highest priority. This would only be usable in the Editor and disabled during runtime to avoid any unintended behaviour.

Viewfinder should state if it's currently being manually set to active in the editor to prevent confusion with the viewfinder saying one thing, while runtime says something else.

**Comment by tiloc** [comment]
Just a thought: Maybe have a drop-down list of the cameras in the preview instead? Maybe in the place where it currently says "Overridden by"

**Comment by ramokz** [comment]
> Just a thought: Maybe have a drop-down list of the cameras in the preview instead? Maybe in the place where it currently says "Overridden by"

That's the idea behind #33.
The feature in this issue is about being able to simple preview a select `PCam` without changing a `Priority` value.
