### ISSUE TITLE
Unexpected Camera Behavior With Jolt Physics Installed and Active

### ISSUE THREAD

**Issue by ElektroFox** [ramokz/phantom-camera#240]
### Discussed in https://github.com/ramokz/phantom-camera/discussions/239

<div type='discussions-op-text'>

<sup>Originally posted by **ElektroFox** March 24, 2024</sup>
With JoltPhysics freshly installed, upon restart and testing my scene, the Third Person PCam that was working just fine now zooms into the character capsule as if it were assuming the position of a first person camera. I cannot find anything in the documentation for this. Any idea on how to fix this? Is it a bug?

EDIT: I reset to Godot's default physics, then back to Jolt (restarting the editor for each) and all of a sudden it is working. I changed nothing except for the physics engine. Quite odd. I would provide footage, but I did not have the ability to recreate the bug while attempting to re-record for expediency's sake. If I am able to replicate the issue, I will update this post with video.

EDIT 2: After modifying some of the spring settings in the PhantomCamera node on my player, the bug has returned. Video below.

https://github.com/ramokz/phantom-camera/assets/13038096/d0c1bdd2-fef1-478f-afd7-3cb2621843e8

</div>

**Comment by ramokz** [comment]
Closing the issue as I would like to keep the discussion to either a discussion post or an issue, rather than both.
Particularly as this doesn't look like an issue but rather just two physics engines having two different hit collision systems, but the solution is the same in both as mentioned in the discussion post.
