### ISSUE TITLE
Support for per-axis damping

### ISSUE THREAD

**Issue by trevorstarick** [ramokz/phantom-camera#255]
### Project Type

2D, 3D

### Feature Description

The ability to set the damping value per axis. Currently the value is shared between x, y in 2D and x, y, z in 3D.

### Use Cases

Currently I'm using it so the X axis damping is much higher than my Y and Z axis for a simple 2D platform using the 3D camera.

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

All the time - the feature can be very useful for a varity of different projects

### (Optional) Proposed Solution

I've implemented a working version here: https://github.com/trevorstarick/phantom-camera/tree/feat-per-axis-damping-value

**Comment by ramokz** [comment]
Closing this.

Not because it's a bad idea, but because it's already implemented for the upcoming release 0.7 :wink: 

Can see a preview of it [here](https://elk.zone/mastodon.gamedev.place/@marcusskov/112246081440904742)
