### ISSUE TITLE
Follow Damping with different values only applies smoothing in the global axis

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#259]
### Issue description

**For 3D scenes**

When enabling `Follow Damping` and supplying different values, e.g. `Vector3(0.1, 0.1, 0.6)`, in the `Follow Damping Value` property, the damping movement doesn't update the camera's local position consistent once the camera starts moving.

### Steps to reproduce

1. Add a simple `PCam3D` setup with a movable character
2. Set a `PCam3D` follow target to the movable character
3. Apply a `Follow Damping Value` with `Vector3(0, 0, 0.6)`
4. Observe how the camera follows its target here
5. Adjust the follow offset so that the `PCam3D` is sitting diagonally or sideways from its follow target
6. Readjust the `PCam3D`'s rotation so it points towards its target again

Both examples below has:
- `Follow Damping Value` = `Vector3(0, 0, 0.6)` 

### Normal Version
- `Follow Offset` = `Vector3(0, 2, -2)`

https://github.com/ramokz/phantom-camera/assets/5159399/c1d74fdb-cde8-459c-8f9b-97bce030fb27

### Issue Version
- `Follow Offset` = `Vector3(-2, 2, 0)` 
- Rotated to point towards the target

https://github.com/ramokz/phantom-camera/assets/5159399/b30edd46-5008-4cd9-969a-7bff6896e45d

As seen, the damping is following the global coordinates rather than its local x, y, z positions, which makes the damping value a bit misleading and, likely, not lead to the intended experience.

**Comment by ramokz** [comment]
There are a few ways I can think of resolving this issue, but none of them seem lead to a perfect solution.

From the issue video example above, if you make damping apply to the camera's local positioning, then that resolves the issue when moving in the x-axis.

![image](https://github.com/ramokz/phantom-camera/assets/5159399/1e350271-b226-4365-92f4-c5363ea02734)

But conversely, if the camera is slightly tilted to point downwards, like above, then that would mean the y and z-axis damping is now pointing in a local forward and upward axis, which might not be desired either.

Current thinking is to allow the user to set which axis should be local, be it individual axis (e.g. x only) or multiple (e.g. xz only).

**Comment by ZenithStar** [comment]
What's an application where you would want to have independent dampening magnitudes per axis? The only one I can think of is maybe have higher dampening on the vertical axis in order to accentuate the feeling of falling, but I don't think it works like that. 
Video with dampening (0.1, 1.0, 0.1): 
[2024-04-27 06-30-19.webm](https://github.com/ramokz/phantom-camera/assets/12200619/114521b5-93c1-432a-b72d-866c02ec49c7)

**Comment by ramokz** [comment]
Can imagine a few instances where that might be desired, but, obviously, it's entirely dependent on what direction a dev wants for their camera.

@trevorstarick suggested it a little while ago (#255), after it had already been implemented in the 0.7 branch, so maybe there's a particular use-case?

**Comment by trevorstarick** [comment]
I was originally looking for a way to limit the aggressive-ness of the x-axis follow for a platformer I'm working on.

**Comment by ramokz** [comment]
Does the current implementation match what you were looking for, or are there any changes you miss?

**Comment by trevorstarick** [comment]
Yup, it's pretty much the same implementation that I had. I'm still messing around with the core camera design, so if there is anything that I'm missing, I'll probably end up forking and then making a PR for any features I add/extend.

**Comment by ramokz** [comment]
Nice!

Will close the issue for now as no one has complained about it yet, but anticipate someone will down the line.
