### ISSUE TITLE
Unannounced change: Removal of set_limit(side, value)

### ISSUE THREAD

**Issue by CantyCanadian** [ramokz/phantom-camera#270]
### Issue description

It seems that the new version of the plugin has the set_limit and get_limit functions removed. Was this an intended removal? If so, is there a reason why? I use those functions and I cannot seem to find an explanation. I re-added them to my code in the meantime.

### Steps to reproduce

This is in main right now.

**Comment by ZenithStar** [comment]
The API has changed to `pcam.limit_left = -1000.0`, etc: https://github.com/ramokz/phantom-camera/blob/7c358dd93df5cde3a9916c14c88c897527c50ff6/addons/phantom_camera/scripts/phantom_camera/phantom_camera_2d.gd#L325
The docs are still out of date

**Comment by ramokz** [comment]
This was done a while back, but remember the intent was due to the simplified property system where, as @ZenithStar says, you can assign the value directly to a given side.

That said, don't see a reason why having a general setter and getter where you pass both a side and a value as a parameter can't be added in again. So look into adding that in soon in a hotfix.

I did also discover a bug with setting the `Limit Value` with a number, so will be doing a fix for that as well.

The docs being out-out-date is definitely an oversight, so thanks for raising that!

**Comment by CantyCanadian** [comment]
Is there a changelog of function name changes between versions? I made a C# wrapper for the gd PhantomCamera and thus name changes will break without warning.

**Comment by ramokz** [comment]
I was considering making a list before the release, but decided not to in the end, as it would take quite some time to do. Given, writing the release notes and documentation were quite a large task alone. So didn't think it would have been worth the effort, as I imagined most wouldn't use many of the functions, and so would make for a relatively painless transition.

What I didn't know was that creating C# wrappers was a thing that people did, let alone something you could do, until yesterday…

**Comment by ramokz** [comment]
`set_limit` and `get_limit` should now be in the latest hotfix

**Comment by CantyCanadian** [comment]
> I was considering making a list before the release, but decided not to in the end, as it would take quite some time to do. Given, writing the release notes and documentation were quite a large task alone. So didn't think it would have been worth the effort, as I imagined most wouldn't use many of the functions, and so would make for a relatively painless transition.
> 
> What I didn't know was that creating C# wrappers was a thing that people did, let alone something you could do, until yesterday…

It was the safest way to interact with a PCam in C# since I gotta magic-string every function calls, so might as well have the magic strings in a single class rather than scattered around. If you want the file, as a way to either add very rough C# support or get inspired to make your own, I can give it to you.

> `set_limit` and `get_limit` should now be in the latest hotfix

Thank you!

**Comment by ramokz** [comment]
Closing this issue as the original report is now merged and released.

**Comment by CantyCanadian** [comment]
[PhantomCamera2D.zip](https://github.com/user-attachments/files/16053939/PhantomCamera2D.zip)

Oops, I missed the last message. Here's the file, though it hasn't been updated in a bit so might not be up to date.

**Comment by ramokz** [comment]
This is great, thanks for sharing this!
Will look into getting C# support out-of-the-box at some point.
