### ISSUE TITLE
Upstream plugin update notification

### ISSUE THREAD

**Issue by kelteseth** [ramokz/phantom-camera#271]
### Project Type

Editor

### Feature Description

The idea of having a notification is cool, but has some flaws:

- Now every team member asks me "_What should I click_" when the update message appears. After every update. 
- This should be more like in the warnings tab of the editor that your plugin is outdated
- It would be cool to have this feature upstream as a regular Godot feature. It would be bad if now every Godot plugin starts creating their own updater...

👋

### Use Cases

-

**Comment by ramokz** [comment]
> Now every team member asks me "What should I click" when the update message appears. After every update.

That is the intent behind the ability to [disable the updater prompt for the setting](https://phantom-camera.dev/editor-updater#updater-settings), so you can turn it off if you would rather not see it when it occurs.
The challenge is to avoid obfuscating that there is an update, as fixes and improvements go in. But to your point, it can also become a distracting if you aren't concerned about updates at certain stages.

> This should be more like in the warnings tab of the editor that your plugin is outdated

The current updater is based on the editor from [dialogue_manager addon](https://github.com/nathanhoad/godot_dialogue_manager), so it follows most of the same logic as the one there. Haven't explored that idea of applying it to the tab, but think it's a sound suggestion. Would imagine it would be simple to change, but will need to look into it when time allows. If you've got any pointers to it, then that would be very welcome!

> It would be cool to have this feature upstream as a regular Godot feature. It would be bad if now every Godot plugin starts creating their own updater...

There is a [Godot proposal](https://github.com/godotengine/godot-proposals/issues/8451) for this, but it's a complicated thing that's still being figured out. The updater
