### ISSUE TITLE
Possible 0.6 -> 0.7 migration problem on Windows

### ISSUE THREAD

**Issue by victorlapin** [ramokz/phantom-camera#274]
### Issue description

After successfully migrating plugin from 0.6.4 to 0.7.0.4, I've started to get a couple of editor warnings when opening my project.

`drivers/windows/file_access_windows.cpp:127 - Case mismatch opening requested file 'phantom_camera_2D.gd', stored as 'phantom_camera_2d.gd' in the filesystem. This file will not open when exported to other case-sensitive platforms.`

I believe it's not a Phantom Camera issue per se, it's more of a heads up - due to case-insensitivity of Windows filesystem, plugin migration can lead to possible problems with exported builds. 

I'd suggest any Windows users remove the plugin completely, commit that change to Git, and then re-apply Phantom Camera.

### Steps to reproduce

Create any 2D scene with Phantom Camera 0.6.x, commit it to a Git repository, then migrate to 0.7.x (optionally, commit it as well).

**Comment by ramokz** [comment]
The error log reads like an excerpt of the issues mention in #263 #272 and #275.
Tempted to say it's the same issue?

**Comment by victorlapin** [comment]
Looks like it, yes

**Comment by ramokz** [comment]
Nice! Closing the issue in that case.
