### ISSUE TITLE
Auto follow distance is broken

### ISSUE THREAD

**Issue by TCROC** [ramokz/phantom-camera#277]
### Issue description

Auto follow distance is broken.  You can see that when setting it to true in the example project, it doesn't work.  I put in a PR for a fix here: https://github.com/ramokz/phantom-camera/pull/276

Looks like an incorrect field assignment got caught up in the refactor

### Steps to reproduce

NA

### (Optional) Minimal reproduction project

NA

**Comment by ramokz** [comment]
Fixed in #276 

Thanks again!
