### ISSUE TITLE
Camera3DResource using wrong layers for Cull Mask?

### ISSUE THREAD

**Issue by tiloc** [ramokz/phantom-camera#290]
### Issue description

The inspector for Camera3DResource is showing the 32 layers for the collision cull mask. Shouldn't it display the 20 layers of the visualisation cull mask, as Camera3D does?

### Steps to reproduce

Add a PhantomCamera3D with a Camera3DResource to the project. Inspect the Camera3DResource.

**Comment by ramokz** [comment]
Correct, it's using `export_flags_3d_physics` but it should be `export_flags_3d_render`, which has the correct number of layers.
Not a priority, as I doubt 20+ layers is a common scenario.

**Comment by tiloc** [comment]
> Correct, it's using `export_flags_3d_physics` but it should be `export_flags_3d_render`, which has the correct number of layers. Not a priority, as I doubt 20+ layers is a common scenario.

Of course I can work around it, but it makes life harder because it means the tooltips with the layer names are showing nonsense (I have culling masks named realworld, minimap, etc., but now it is showing player, enemies, etc.)

**Comment by ZenithStar** [comment]
Yeah. I remember seeing this a while back, but I'm only using one mask so far, so it didn't particularly bother me 
![image](https://github.com/ramokz/phantom-camera/assets/12200619/2e3d73f7-dbaf-46d8-ad88-d0e93d829260)

**Comment by ramokz** [comment]
Closing issue.
Will be part of the 0.7.1 release.
