### ISSUE TITLE
Allow nesting of cameras withinin Nodes

### ISSUE THREAD

**Issue by willdayble** [ramokz/phantom-camera#305]
### Project Type

2D

### Feature Description

Allow for PhantomCamera to be placed within a Node / somewhere other than the root node. Having more than a few cameras makes the node tree messy and hard to manage.

### Use Cases

Most 2D Games have something like:
- GameSystems
- World
-- Levels
-- Player

Would be great to have something like:

- GameSystems
-- PhantomCameraStuff
-- Etc
- World
-- Levels
--- Level
--- PhantomCameras
-- Player

### (Optional) Proposed Solution

Best: Allow camera nodes anywhere in the scene tree
Minimal: Have a Node2D called `PhantomCamera` that holds all the cameras and Host nodes

**Comment by ramokz** [comment]
Unless I'm misunderstanding the point, that is already possible?

**Comment by willdayble** [comment]
Yeah turns out I am a total dum dum.

**Comment by willdayble** [comment]
LOL 😅

**Comment by ramokz** [comment]
Happens to the best of us  :smile:
