### ISSUE TITLE
Bug that can cause a PhantomCamera3D set to _not_ tween on load to tween anyway (and suggested fix)

### ISSUE THREAD

**Issue by llittle3701** [ramokz/phantom-camera#315]
### Issue description

NOTE: This issue was written for v.0.7.0.6. I have not yet dived into the latest release.

I'm using PhantomCamera3D in an unorthodox way and believe I've found a bug. Looks to be an indentation typo really. In `phantom_camera_host.gd`'s `pcam_added_to_scene function`, if a pcam has been set to _not_ tween on load, it has its `_has_tweened` property set to true. This is so that the pcam will not have its `_trigger_pcam_tween` property set to true as part of the `_assign_new_active_pcam` function

![Capture2](https://github.com/ramokz/phantom-camera/assets/15115053/6696ad94-19aa-43ad-9480-f53371fa03b9)

Now I believe the error lies in the `_find_pcam_with_highest_priority` function. It iterates through the list of pcams to find the one with the highest priority to set the active pcam. However, line 233 is outside of the scope of the if statement on line 230. This causes ALL pcams in the list to have their `_has_tweened` property set to false. I don't believe this is the intended behavior.

![Capture1](https://github.com/ramokz/phantom-camera/assets/15115053/d93eee4a-cf60-49c5-875a-73fac003b3aa)

The fix here is to indent lines 233 (and probably 235 as well) as I believe that was the intended functionality.

![Capture3](https://github.com/ramokz/phantom-camera/assets/15115053/79560b87-e06e-4f20-9b5c-fdc8e4ea65bd)

### Steps to reproduce

I haven't made a test project for this, but I believe this will reproduce.

1. Make a scene (I'll call it the parent scene) containing a regular Camera3D
2. In code, instantiate another scene (at runtime) containing a PhantomCamera3D as a child of a node in the parent scene (see example image below of my setup). Make sure the PhantomCamera3D is set not to tween on load in the editor.
3. Run the parent scene. When the PhantomCamera3D appears, the Camera3D will still tween its way to the PhantomCamera3D

![setup](https://github.com/ramokz/phantom-camera/assets/15115053/f643ed07-50b8-4267-a143-4a1f04c06526)

**Comment by ramokz** [comment]
Thanks for the report! Was able to replicate the issue.

From some quick tests, this appears to be specific to `Third Person` follow.
The other follow modes do not seem to trigger this.

Think the solution you proposed works in your case, but tested it and found that it seems to only consistently work with a particular set of `PCam` priorities within a scene. 

Submitted a PR (#319) that should resolve it for various scene setups.
