### ISSUE TITLE
Regression when setting third person rotation at scene creation

### ISSUE THREAD

**Issue by Paul-Griffin-1517-1** [ramokz/phantom-camera#329]
### Issue description

In my project there is a "PlayerSpawner" scene that adds the player character and sets the initial PhantomCamera rotation. Since v0.7.0.6 the implementation has broken.

### Steps to reproduce

In the minimal reproduction project main branch, go to PlayerSpawn.gd. Await a short timer at the commented line to disable the error. Alternatively, on_load_camera_rotate.call_deferred(). This code as is worked in PhantomCamera v7.0.6 (and can be seen in the other branch.)
You can rotate the camera with the right stick of a controller or with your keyboard arrow keys.

### (Optional) Minimal reproduction project

https://github.com/Paul-Griffin-1517-1/PhantomCamera-Rotation-Bug-MRP
Godot 4.2.2, includes branch with latest release of PhantomCamera (where issue is present) and with an earlier version (where the issue is not).

**Comment by ramokz** [comment]
Looks like it's working as expected in 0.7.2 when you remove the line `player.get_node("ThirdPersonCamera").on_load_camera_rotate(rotation_degrees.y)` inside `PlayerSpawn.gd`.

https://github.com/ramokz/phantom-camera/assets/5159399/b42551b1-7738-4f73-9bc2-7279a381b048

**Comment by ramokz** [comment]
It's likely a race condition where you're setting the rotation before the `PCam3D` gets reattached to the `SpringArm3D`.
In the previous release (pre-7.1), it would do some setup logic in the `_process` but that is now happening inside `_ready`. 

If you add an await function above the `on_load_camera_rotate` function, it should work in the 0.7.2 release:

```gdscript
await player.get_node("ThirdPersonCamera").ready
player.get_node("ThirdPersonCamera").on_load_camera_rotate(rotation_degrees.y)
```

**Comment by Paul-Griffin-1517-1** [comment]
>  it would do some setup logic in the _process but that is now happening inside _ready.
That would explain it! I don't think it was mentioned in the patch notes. Seems to have fixed the issue, thanks!

**Comment by ramokz** [comment]
Closing as the issue seems to have been resolved.
