### ISSUE TITLE
cant load phantom camera

### ISSUE THREAD

**Issue by MomoLassticot** [ramokz/phantom-camera#337]
### Issue description

i just downloaded the addons and i cant use it, i just get this error again and again:
![image](https://github.com/ramokz/phantom-camera/assets/133434481/bddc13ce-25f5-4608-aeeb-ab5b846a0cd2)

### Steps to reproduce

load the addons from the asset librairy or the github

**Comment by rugia813** [comment]
same thing just happened to me, I closed godot and reopen project seems to fix it

**Comment by ramokz** [comment]
Think this is a dup of #323?
