### ISSUE TITLE
Camera Springarm / 3rd Person Follow

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#34]
# Problem
`PhantomCamera3D` is currently living freely in space as it moves around. While this is fine in many cases, there are also scenarios where there's a desire to make the camera unable to go through colliders in a scene, which would otherwise cause it to go out of bounds and through geometry. Leading to potentially undesired results. 

# Proposed Solution
Add a new follow mode parameter to `PhantomCamera3D` that functions like a `SpringArm` to provide collisions. Essentially working as a base 3rd person follow mode.

**Comment by ramokz** [comment]
Moving to another milestone as aim and scope has changed / increased following some additional research.

**Comment by LucasArusiewicz** [comment]
maybe this can help
https://docs.godotengine.org/en/stable/classes/class_springarm3d.html

**Comment by ramokz** [comment]
Thanks! Yeah, the current thinking is to leverage the built-in `SpringArm3D` node and essentially just make the `PhantomCamera3D` instantiate and utilize it. Haven't explored if there will be any complications with doing that, so left the proposal somewhat vague in case there are undesired results and would require a more bespoke solution.

**Comment by mrsinistar64** [comment]
I absolutely love this camera addon and what it can do but I can't seem to get it to work with the SpringArm3D node, so it would really awesome to see this get implemented in the future.  Thank you for your work on this so far!

**Comment by LucasArusiewicz** [comment]
I don't know how the implementation is going, but in this plugin the demo scene player uses ArmSpring, perhaps it could be a starting point.

Plugin: [Terrain3D](https://github.com/TokisanGames/Terrain3D/tree/main)

I'm not yet phantom-camera in any project, but it's on my radar. I greatly appreciate and admire everything that has been developed so far.

**Comment by ramokz** [comment]
> I don't know how the implementation is going, but in this plugin the demo scene player uses ArmSpring, perhaps it could be a starting point.
> 
> Plugin: [Terrain3D](https://github.com/TokisanGames/Terrain3D/tree/main)
> 
> I'm not yet phantom-camera in any project, but it's on my radar. I greatly appreciate and admire everything that has been developed so far.

Thanks for the share! They seem to have done a similar approach to what I've been thinking.

There is [a branch](https://github.com/ramokz/phantom-camera/tree/follow-third-person) with the latest progress on the feature. In it, there is a demo scene called `3DFollowThirdPersonExampleScene`, which currently has a working 3rd person orbit camera using a SpringArm implemented. It is missing damping functionality, which is what's currently being worked on.

The feature is the current priority at the minute, and hoping it'll see a proper implementation in the near future.
