### ISSUE TITLE
PhantomCamera2d in instanced scene cannot be moved

### ISSUE THREAD

**Issue by oxeron** [ramokz/phantom-camera#350]
### Issue description

I use an instanced scene as a template for my levels.
In the base scene, I have the following setup :
![Capture d’écran 2024-07-16 à 22 01 14](https://github.com/user-attachments/assets/9e76c8c0-72ec-45a0-9cf3-36446bbc0f55)

In the instanced scene I cannot change the transform property of my PhantomCamera2D node :
![Capture d’écran 2024-07-16 à 22 00 29](https://github.com/user-attachments/assets/31d67246-6c43-4988-a990-3eaec07d0005)

If I add a new PhantomCamera2D2 in the scene, I can change its property as I want

Is there a bug with the instanced scene ?

### Steps to reproduce

In a scene:
Add a Camera and PhantomCameraHost
Add a PhantomCamera2D

Create a new instanced scene with those nodes
The PhantomCamera2D transform property cannot be modified

**Comment by oxeron** [comment]
I opened the house1-room1.tscn file and I found a property that was still present:
follow_target = NodePath("../Characters/Player")

I removed the line and it works well

**Comment by ramokz** [comment]
It's a bit tricky to tell without seeing all the properties, particularly `Follow Target`, but my guess would be that you set a `Follow Target` in the initial `PCam2D` instance before creating an instantiated scene with that and the other nodes.

At least, that's what your second comment seems to suggest.

**Comment by oxeron** [comment]
I think that was the issue, nothing to be done here :)
Sorry for the noise
