### ISSUE TITLE
Freed Follow Target no longer valid, causing error when returning position 

### ISSUE THREAD

**Issue by luiscesjr** [ramokz/phantom-camera#353]
### Issue description

I'm facing this issue on the phantom_camera_2d, that sometimes the script tries to update the position of a freed instance. 

My game is battle royale style game, so whenever the player dies for example, you get to choose a new character to respawn. In this case I queue_free the old instance and add the new choosen one.

But it seems the timing of this is missaligned with phantom_camera, specifically in this place I've been getting errors:

```
func _target_position_with_offset() -> Vector2:
	return follow_target.global_position + follow_offset
```

![image](https://github.com/user-attachments/assets/c599f581-bb53-4380-91da-43095eac5d46)

This is line 668 of the phantom_camera_2d.gd script. Could it be added a check to see if the target is still valid before returning the position? Maybe a is_instance_valid(follow_target) or something similar? 

OR maybe I should, before freeing change targets, and that's it? It's been my small hack-around for now. 

### Steps to reproduce

Queue_free() a Node and sometimes the phantom camera won't know it's been freed before changing targets.

**Comment by ramokz** [comment]
Think it's a case of where the `PCam` doesn't register that it's follow target has been freed, which isn't ideal for cases like yours that I can imagine is quite common.

If you replace the `phantom_camera_2d.gd` script, inside `addons/phantom_camera/scripts/phantom_camera`, with the one below, does that resolve the issue?
[phantom_camera_2d.gd.zip](https://github.com/user-attachments/files/16446564/phantom_camera_2d.gd.zip)

**Comment by ramokz** [comment]
Sorry, forgot to realise that I was in the wrong branch when I sent the file. It has a some under-the-hood changes that would be incompatible with the changes in other files.

Ideally, would want to avoid having to check if an instance is valid every frame, as it's an additional checker that's pricier than a simple boolean checker (is_queued_for_deletion()). So would only consider that as a last resort.

Would you be able to share the scene and script that you're encountering the issue in? Would be easier to test locally than hypothesising solutions.
