### ISSUE TITLE
Disabling the plugin reports an invalid access error

### ISSUE THREAD

**Issue by bUsernameIsUnavailable** [ramokz/phantom-camera#357]
### Issue description

When the plugin is disabled, Godot will print the following error:

![image](https://github.com/user-attachments/assets/c452f873-ee46-4ef6-a738-36bade449e5a)

This can be easily fixed by rewriting the `_exit_tree` function inside plugin.gd to perform the inverse operations of `_enter_tree` in the correct order.

Here is the entire rewritten function:
```gdscript
func _exit_tree() -> void:
	scene_changed.disconnect(_scene_changed)
	scene_changed.disconnect(editor_panel_instance.viewfinder.scene_changed)
	panel_button.toggled.disconnect(_btn_toggled)

	remove_control_from_bottom_panel(editor_panel_instance)
	editor_panel_instance.queue_free()

	remove_node_3d_gizmo_plugin(pcam_3D_gizmo_plugin)

	remove_custom_type(PCAM_HOST)
	remove_custom_type(PCAM_3D)
	remove_custom_type(PCAM_2D)

	remove_autoload_singleton(PHANTOM_CAMERA_MANAGER)
```

### Steps to reproduce

Enable the Phantom Camera plugin and then either disable it manually or simply close Godot.

**Comment by ramokz** [comment]
Thanks for the report!

Resolved in #358
