### ISSUE TITLE
Cannot call method 'is_queued_for_deletion' on a null value.

### ISSUE THREAD

**Issue by tylercritchlow** [ramokz/phantom-camera#367]
### Issue description

Cannot call method 'is_queued_for_deletion' on a null value. This keeps happening when trying to do look at group in 3D.

### Steps to reproduce

add nodes to look at group option in PhantomCamera3D node.

### (Optional) Minimal reproduction project

[prototypegame.zip](https://github.com/user-attachments/files/16683851/prototypegame.zip)

**Comment by ramokz** [comment]
Can see the issue.

It's happens because there is an array of nodes assigned to the `Group Follow Targets`, which is only visible when re-enabling that follow mode or from the `.tscn` text file, where the addon doesn't properly account for that.

Should be a simple fix.

**Comment by ramokz** [comment]
To resolve it locally before the fix gets released, you can just change the `Follow Mode` to `Group`, clear the `Follow Targets` array and then set the `Follow Mode` back to `None`.

**Comment by ramokz** [comment]
Should be resolved with the changes in #381 raised in #374.
