### ISSUE TITLE
Framed Camera in 2D that follows diagonal movements 

### ISSUE THREAD

**Issue by lafitteque** [ramokz/phantom-camera#372]
### Project Type

2D

### Feature Description

Currently, when you get to a border of the frame in Framed mode for a PhantomCamera2D, the position of the canvas relative to the player will not change while you stay on the porder of the frame. This can lead to weird situations like going on the bottom right corner of the frame and, once you get there, even if you go in the bottom left direction, the camera will not go to the left.

Without the feature :
https://github.com/user-attachments/assets/10bd431a-e135-4785-a0f9-9270ea021931

With the feature :
https://github.com/user-attachments/assets/c094f64b-b621-43a3-be26-d82b57601818

### Use Cases

The idea of the framed camera is that it follows the player's movement. In the current version of this addon, the camera will not always follow the player's movent if on the borders of the frame. 
The behaviour desribed is what I was looking for when I downloaded the addon. I think it is one of the main points of the framed camera. 

### (Optional) Proposed Solution

Replacing the condition at line 600 of res://addons/phantom_camera/scripts/phantom_camera/phantom_camera_2d.gd by the following ones seems to work for me.

```
						elif _get_framed_side_offset().x != 0  and _get_framed_side_offset().y == 0:
							follow_position = target_position
							_follow_framed_offset.y = global_position.y - _target_position_with_offset().y
						elif _get_framed_side_offset().y != 0 and _get_framed_side_offset().x == 0 :
							follow_position = target_position
							_follow_framed_offset.x = global_position.x - _target_position_with_offset().x
						else : 
							follow_position = target_position
```

**Comment by ramokz** [comment]
There is an upcoming refactor task for Framed Follow in #161 that aims to solve things like this.

**Comment by ramokz** [comment]
Your proposal does seem to partly solve one of the main issues, so happy to add that in to alleviate the current approach until it can be fully looked at.

**Comment by ramokz** [comment]
Feel free to open a PR to add that small change in (if you want contribution credit); otherwise, I can add it in for the next release linking to this post.

**Comment by lafitteque** [comment]
It's my first time making a PR so I hope I didn't mess up. In any case, if the PR is messed up, you can add it in for the next release like you said.

**Comment by ramokz** [comment]
It all looks great, so no need to worry :slightly_smiling_face: 

Thanks for sharing the improvement!

**Comment by ramokz** [comment]
Believe the PR solved the problem this issue described, so closing it.

If I misunderstood, please do let me know and can reopen this.
