### ISSUE TITLE
Errors anytime you switch scenes after adding a Camera3D and a PhantomCameraHost to the scene.

### ISSUE THREAD

**Issue by Coded-Eye** [ramokz/phantom-camera#383]
### Issue description

Gets 100+ errors each time I switch scenes inside the editor

"res://addons/phantom_camera/scripts/panel/viewfinder/viewfinder.gd:201 - Cannot call method 'get_camera_3d' on a null value."

reproduction in video 
https://github.com/user-attachments/assets/1966eba6-254d-4f16-9bbd-d2bd97125c7f

### Steps to reproduce

1. Create project
2. Install Phantom-Camera and Activate it
3. Make two 3d scenes
4. Add in one the scenes a Camera3d and PhantomCameraHost using the "Phantom Camera tab".
5. Switch the scene to any other scene

**Comment by ramokz** [comment]
Have noticed this as well since using Godot 4.3.
Planning on having this resolved in the 0.8 release, as it's an annoying error spam indeed.

Thanks for making a ticket so it can be better tracked!
