### ISSUE TITLE
[2D] Group follow mode is biased towards first target when multiple targets are present

### ISSUE THREAD

**Issue by TheWathis** [ramokz/phantom-camera#396]
### Issue description

When two nodes (and probably more) are present in the `Follow Targets` variable of a `PhantomCamera2D` with a `Follow Mode` set to `Group`, the camera will be biased towards the first target

![image](https://github.com/user-attachments/assets/3b2fed79-2a46-43f0-ac7b-8e1be95ac31e)

### Steps to reproduce

- Add a `PhantomCamera2D`
- Set the `Follow Mode` to `Group`
- Add the two (or mode) nodes to `Follow Targets`
- Swap the order of the nodes to better see the bias

**Comment by TheWathis** [comment]
After a bit of digging, it looks like the bias is due to setting the `follow_position` to `rect.get_center()` which is created around the first target. To be perfectly centered, `follow_position` should be set to the mean of every target position

**Comment by ramokz** [comment]
Refactored a fair bit for the 0.8, so the initial issue you shared seems to have already been resolved a little while ago.

But spotted that it was still occurring when `auto zoom` was enabled when doing some repro tests, which should now be resolved as well.

Thanks for calling attention to this!
