### ISSUE TITLE
Repeated Errors on Switching Scenes in Editor

### ISSUE THREAD

**Issue by SkuttleBugg** [ramokz/phantom-camera#401]
### Issue description

I see you are already aware of the bug that generates over 100 errors when switching scenes inside the editor for the Phantom Camera 3D but I would also like to report that the same thing happens with the Phantom Camera in 2D. 

### Steps to reproduce

1. Create two scenes ( in 2D )
2. Install PhantomCam and enable it
3. Add Phantom Camera
4. Switch between the two scenes in editor ( it will keep creating over 100 errors when you switch scenes )

**Comment by ramokz** [comment]
This was resolved in #376.
