### ISSUE TITLE
Framed Mode Deadzone not working when Viewport size differs from Window size

### ISSUE THREAD

**Issue by TTMoon** [ramokz/phantom-camera#404]
### Issue description

In **Framed Mode**, the **Deadzone** does not function correctly when the **Viewport size** and **Window size** are different. It seems the issue may stem from small typos in the `phantom_camera_3d.gd` file.

[Currently, at line **762**:](https://github.com/ramokz/phantom-camera/blob/main/addons/phantom_camera/scripts/phantom_camera/phantom_camera_3d.gd#L762)
```gdscript
var visible_rect_size: Vector2 = get_viewport().get_viewport().size
```
This uses the Viewport size instead of the visible rectangle. It should be corrected to:

```gdscript
var visible_rect_size: Vector2 = get_viewport().get_visible_rect().size
```

Additionally, at **[line 719](https://github.com/ramokz/phantom-camera/blob/main/addons/phantom_camera/scripts/phantom_camera/phantom_camera_3d.gd#L719)** the same issue occurs

### Steps to reproduce

1. Set up a 3D scene using the Phantom Camera in Framed Mode.
2. Adjust the Window size to something different from the Viewport size (e.g. Viewport: 1920x1080, Window: 1600x900)
3. Observe that the Deadzone does not behave correctly.

**Comment by ramokz** [comment]
Thanks for raising this! It was a typo indeed.
