### ISSUE TITLE
In example scenes, middle clicking gives me an error: Invalid access to property or key 'keycode' on a base object of type 'InputEventMouseButton'.

### ISSUE THREAD

**Issue by dragon3025** [ramokz/phantom-camera#413]
### Issue description

Middle clicking gives me an error in the example scenes: `Invalid access to property or key 'keycode' on a base object of type 'InputEventMouseButton'.`.  The error is on line 92 in `player_character_body_2d_4.3.gd`.

### Steps to reproduce

- Add Phantom Camera to a new project and enable plugin.
- Open `2d_example_scene.tscn` and run it.
- Middle click the mouse.

**Comment by ramokz** [comment]
Resolved in #415 

Thanks for the report!
