### ISSUE TITLE
Ability to setup viewport options for the preview

### ISSUE THREAD

**Issue by Soremwar** [ramokz/phantom-camera#418]
### Project Type

2D, Editor

### Feature Description

Viewport settings should be configurable for the preview tab or inherit these from project settings, otherwise the preview won't match the visual of the game

### Use Cases

When working with pixel art games, the default filter will turn everything into a blurry mess

**Comment by ramokz** [comment]
Could you share what specific viewport or project settings you're thinking of?

**Comment by Soremwar** [comment]
Texture filter for canvas items, setting it to `nearest` specifically

**Comment by ramokz** [comment]
Would you be able to share a small project with a sample scene, so I can see if a potential feature implementation works?

**Comment by Soremwar** [comment]
I create a reproduction based on `examples/example_scenes/2D-4.3/2d_example_scene.tscn`, since it's a perfect example

[reproduction.zip](https://github.com/user-attachments/files/17684497/reproduction.zip)

Only change made was the texture filter on project settings from `linear` to `nearest`

If texture filter on the scene node is set to inherit, the scene is sharp, the preview is blurry

![image](https://github.com/user-attachments/assets/37e9632c-d075-48db-bd6c-b9ed41a40748)

If manually set, the preview will match the scene in both cases

![image](https://github.com/user-attachments/assets/58995c17-ffcd-4f9b-97e0-111a79d9eaf2)

**Comment by ramokz** [comment]
Thanks for alluding to this, it's a nice enhancement to the viewfinder.
