### ISSUE TITLE
Camera Offset Locked to One Axis

### ISSUE THREAD

**Issue by JamesLoyMartin** [ramokz/phantom-camera#424]
### Project Type

2D

### Feature Description

Allowing the Phantom Camera to only follow the follow_target along one axis, and for the 'axis lock' to be toggled on and off during runtime to accommodate different uses. Currently it only follows both x and y positions.

### Use Cases

A popular use case would be 'platform snapping' where the camera only follows the player along the X axis when jumping, and both X and Y when grounded.  This makes the camera 'snap' to platforms. This is used in Donkey Kong Country 2 and the modern ones, and also in Super Mario World and onward.

Here is a preview of it in my game using Phantom Camera:
![platformSnapExamp](https://github.com/user-attachments/assets/77a87387-9d80-4c08-a95d-fcdc0a3b16ec)

This preview just switches the follow_target when jumping to a marker2D that only follows the player's X position, which causes an undesirable small delay as the Marker2D slightly lags behind the player. I'm relying on the damping values to ensure a smooth transition back to the player when switching follow_target.

It would be preferable to lock the camera to the x axis while still following the player during a jump, then unlock the axis when the player lands to allow following both X and Y (would require some kind of tween/damping to get back to the target?)

### (Optional) Proposed Solution

Possibly a bool that locks x or y axis of the follow_target that you could change true or false at any time like the other inspector values.
Maybe use the camera's damping value or tween resource to reference while snaping back into place after the axis is 'unlocked' to avoid an unwanted instant transition.

**Comment by ramokz** [comment]
Think this is a good idea!

Practically, think the solution would be a case of supporting both a property in the inspector to enable/disable individual axis and programmatically in cases where you want to change it during runtime.

Only other comment is that I think the proposal also applies to 3D scenes, hence the added tag.
