### ISSUE TITLE
phantom camera host crash when changing scenes

### ISSUE THREAD

**Issue by lord-muad-dib** [ramokz/phantom-camera#437]
### Issue description

hello, since i have upgraded phantom camera (8.1 and 8.2) i'm having issues while changing scene.
it's a 3d game with few phantom cams around stages. i'm on godot 4.4 + interpolation.

as you can see from the stack:
![phantom3d crash1](https://github.com/user-attachments/assets/8fbd8838-e6bd-4470-8137-e646f4bc07f2)

i've researched it a bit and it seems that at that specific moment, the camera host node is already off the tree. and i've seen issues around here and there about get_tree returning null when being called by something that is already out of the scene.

i suppose that piece of code triggers because phantom cameras are getting freed and the host is trying to find the next in line to activate or something while the scene is changing
putting a condition with is_inside_tree somewhere earlier in the error stack  did infact jump that code entirely. but i'm sure a better fix can be implemented, maybe by disconnecting some signals coming from phantom cams when the phantom camera host exits the tree? (if you don't do it already, that is, haven't checked)

### Steps to reproduce

i am simply using:
`get_tree().change_scene_to_file()` after making sure all my runtime instances are freed

keep in mind that i'm not using phantom cameras inside dynamic instances

### (Optional) Minimal reproduction project

i couldn't reproduce the issue on a minimal project yet, but i'll keep trying

**Comment by ramokz** [comment]
Think it might be worth for the addon to do a null check before accessing the scene tree with `get_tree()`.

Though, I am a bit surprised that there is a scenario where there is not a tree present while the `PCamHost` node is running in the first place.
