### ISSUE TITLE
Packed Scene PCam Origin Incorrect

### ISSUE THREAD

**Issue by gummycookie** [ramokz/phantom-camera#441]
### Issue description

I am hoping I'm using the addon as intended. 

I have one scene called World that has this structure 

* World
  * Camera
    * CameraHost
  * Character (Instanced Scene)
  
 and the Character Scene:
 
 * Character
   * CharacterBody3D
      * Skin
   * PhantomCamera3D
   
 
The PhantomCamera follows the Skin with mode `Simple`  (also tried following CharacterBody3D)

The challenge I'm running into is that the PhantomCamera seems to want to glue itself to the global transform position of the Character Scene when instanced in the World Scene at a different position (noticable with the Easing function on)

It is mostly apparent when trying to Follow Lock on the Z axis which it fixes to the origin point of the Character Scene.

I am able get this to work if I forgo the scene all together and directly tie the nodes to the World scene but this isn't ideal. 

I'm wondering if I'm doing something incorrect with my configuration. 

Note: Nothing in my configuration related to PhantomCamera is controlled by a script.

Thanks a bunch for the addon!

### Steps to reproduce

scaffold a project similar to the node structure I have. 

The example projects in the addon can be the foundation.

**Comment by ramokz** [comment]
I'm not quite sure if I understand the issue.

Have tried setting up a scene with the same structure you wrote and don't see anything unexpected?
<img width="253" alt="image" src="https://github.com/user-attachments/assets/7e8188df-61ce-4e03-a537-e08cdea12eed" />

<img width="254" alt="image" src="https://github.com/user-attachments/assets/f856603b-d9fa-44b1-b11a-f8f2b3cfceda" />

**Comment by gummycookie** [comment]
thanks for getting back so quickly! I just put together a reproduction of the issue here.
https://github.com/gummycookie/phantom_cam_repro

**Comment by gummycookie** [comment]
I think I have figured out the issue and what my expectations were. 

I was assuming that if I had a follow cam with follow lock that it would lock the axis at where the target is based on the targets initial global transform axis. Rather, the phantom cam locks at the position of where the phantom cam is instead. 

Maybe we can clarify this behavior in the documentation but it's something I can work with regardless. 

I will close the issue. Thanks a bunch for the addon!

**Comment by ramokz** [comment]
Yes, the lock is just a way to disable any positional changes of `PCam` once it has a valid follow target. It doesn't take the target's position or rotation into account.

Can add a bit more description to the documentation page to make that clearer.
Thanks for the feedback!
