### ISSUE TITLE
Add tooltip description to PhantomCamera properties

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#55]
# The Problem
All the properties in PhantomCamera classes currently don't have any descriptions for what they do. So the only way to know what each property does is by looking at the wiki documentation, the source code or trial and error.

# Proposed Solution
Add a description to each property that explains what each does.

**Comment by BenjaTK** [comment]
I could do this if it's needed.

**Comment by ramokz** [comment]
That would be great!

I chucked this into the backlog since I couldn't figure out a way to add descriptions to properties defined using `_get_property_list()`, not to mention those added from the `Properties` file, but hadn't spent too long looking into this.

Long term, was thinking of updating the properties to use the new [_validate_property](https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-private-method-validate-property) approach added in Godot 4.2.

**Comment by BenjaTK** [comment]
Hmm. Yeah, I don't think you can do it with _get_property_list. It would work if the variables were in the PhantomCameras scripts and we added documentation comments but since they're in a separate script I'm not sure if it's possible.

**Comment by ramokz** [comment]
That's fine! Will revisit this once the properties get converted down the line.

**Comment by ramokz** [comment]
Closing as it ended up effectively being a duplication of #168
