### ISSUE TITLE
Improve Damping Logic

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#92]
# Problem
The current implementation of the `Damping` parameter is fairly basic and isn't very easy to understand when it comes to knowing how smooth the value is.

# Proposed Solution
Rewrite the logic for how damping works, ideally similar to how [Unity's SmoothDamp](https://docs.unity3d.com/ScriptReference/Vector3.SmoothDamp.html) logic, works.

**Comment by voithos** [comment]
In case it's useful, I recently implemented a version of SmoothDamp in GDScript for a simple smooth camera demo: https://github.com/voithos/godot-smooth-pixel-camera-demo/blob/f1d1515d597eac1d4035b281b897eb389560694f/camera_controller.gd#L25

Feel free to reference or use that code!

**Comment by ZenithStar** [comment]
Currently, the damping is only for the position. Any plans to add rotational dampening?

**Comment by ramokz** [comment]
> Currently, the damping is only for the position. Any plans to add rotational dampening?

Yes! Haven't added it yet, as I wanted to get the Follow Damping logic right first before porting it over to the `Look At` functionality. So will be looked at after the issue here has been resolved.

**Comment by WeaselOnaStick** [comment]
I propose using [Critically Damped Spring Smoothing](https://github.com/keijiro/SmoothingTest) implementation which has both position and rotation implemented

**Comment by ramokz** [comment]
Tried out the Critically Damped Spring Smoothing that @WeaselOnaStick mentioned, but ultimately felt that the Smooth Damp approach was a better fit, as the damping seemed more intuitive to use and felt a _bit_ smoother.

The result became effectively the same as what @voithos shared, with a few minor changes.

Thanks for the help and suggestions all!
